modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
license="MIT"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
