modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
license="MIT"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.66,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
