modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/quek04/The-Undergarden/issues"
license="MIT"
[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
authors="quek"
description='''Deep underground, a forgotten land awaits.'''
[[dependencies.undergarden]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undergarden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
