modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/quek04/The-Undergarden/issues"
license = "MIT"

[[mods]]
modId = "undergarden"
version = "${file.jarVersion}"
displayName = "The Undergarden"
logoFile = "logo.png"
logoBlur = false
authors = "quek"
description = '''Deep underground, a forgotten land awaits.'''
itemIcon="undergarden:deepturf_block"

[[dependencies.undergarden]]
	modId = "neoforge"
	type = "required"
	versionRange = "[20.6.46-beta,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.undergarden]]
	modId = "minecraft"
	type = "required"
	versionRange = "[1.20.6]"
	ordering = "NONE"
	side = "BOTH"

[[mixins]]
	config = "undergarden.mixins.json"
